// Understand the problem:
// Create a game of rock paper scissors that you
// can play against the computer. The game should
// start by asking you for your choice. Your choice
// is then compared in a conditional statement with
// the computer's choice, which is generated by 
// random. If you win the round, you get a point and
// vice versa. This process should repeat in a loop
// for some set number of rounds or until one person
// reaches the desired number of wins, which should
// then end the game and display a message in the
// console telling you whether you won or lost the
// game.

// Odin's pseudocode
// 1. Write a function that returns the computer's
//    choice for a given round. This value is
//    calculated based on the built-in random function
// 2. Write a function that returns the user's choice
//    for a given round. This function, when called,
//    simply gets input from the user and returns it.
// 3. Initialize two variables with the value 0 to keep
//    track of the players' scores.
// 4. Write a function that plays out the round. The
//    function should take the user's choice and the 
//    computer's choice and return nothing, but will
//    compare the choices with each other, declaring 
//    the winner by displaying an appropriate message,
//    and incrementing the appropriate score count
// 5. Write a function that plays out the game. The 
//    game will play out 5 rounds and essentially, you
//    are calling all the functions the same way up until
//    this point 5 times. Use a loop for this, or call the
//    functions in a particular order and using variables 
//    to keep track of the values for certain rounds(?)


function getComputerChoice() {
    let computerChoice = Math.floor(3*Math.random())
    return (computerChoice == 0 ? "rock" 
    : computerChoice == 1 ? "paper" : "scissors");
}

function getUserChoice() {
    let userChoice;
    while (userChoice != "rock" && userChoice != "paper" && userChoice != "scissors") {
        userChoice = prompt("Pick one: Rock, Paper, or Scissors? (all lowercase please): ");
        if (userChoice == "" || userChoice == null) {
            continue;
        }
        else {
            userChoice = userChoice.toLowerCase();
        }
    }
    return userChoice;
}

getUserChoice()