// Understand the problem:
// Create a game of rock paper scissors that you
// can play against the computer. The game should
// start by asking you for your choice. Your choice
// is then compared in a conditional statement with
// the computer's choice, which is generated by 
// random. If you win the round, you get a point and
// vice versa. This process should repeat in a loop
// for some set number of rounds or until one person
// reaches the desired number of wins, which should
// then end the game and display a message in the
// console telling you whether you won or lost the
// game.

